namespace: demo
name: demoapp
svcname: demoappsvc
env:
  HTTP_ADDR: :8080
acr:
  uri: "acr6ppmfq4towtku.azurecr.io"
  image: demoapp
  tag: latest
  pull: Always
deployment:
  container:
    name: go
    port: 8080
service:
  type: LoadBalancer
  port: 80
