name: IaC Security Checks
env:  
  ENVIRONMENT_NAME: "${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}"
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    paths: 
      - 'infra/**' 
      - '.github/workflows/checksIaC.yaml'
  push: 
    branches-ignore:
      - main
    paths: 
      - 'infra/**' 
      - '.github/workflows/checksIaC.yaml'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  Setup_Job:
    runs-on: ubuntu-latest
    outputs:
      output_env: ${{ steps.set-variable.outputs.fromenv }}
    steps:
      - name: getvariable
        id: getvariable      
        run: |
          echo "::set-output name=fromenv::${{ env.ENVIRONMENT_NAME }}"
  security_scanning:
    runs-on: ubuntu-latest 
    needs: [Setup_Job]
    environment: needs.Setup_Job.outputs.output_env
    steps:
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./infra
        check: CKV_AZURE_4 #,CKV_AZURE_5,CKV_AZURE_6,CKV_AZURE_7,CKV_AZURE_8 # optional: run only a specific check_id. can be comma separated list
        soft_fail: false # optional: do not return an error code if there are failed checks
        download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
        framework: bicep # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
        #file: sec-plan # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
        #log_level: DEBUG # optional: set log level. Default WARNING
  